// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

// Injectors from injector.go:

func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepo := NewSimpleRepo(isError)
	simpleService, err := NewSimpleService(simpleRepo)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabaseRepository() *DatabaseRepo {
	databasePostgreSQL := NewDatabasePostgre()
	databaseMongoDB := NewDatabaseMongoDB()
	databaseRepo := NewDatabaseRepo(databasePostgreSQL, databaseMongoDB)
	return databaseRepo
}
